# 日志相关配置
logging:
  charset:
    console: utf-8
    file: utf-8
  file:
    path: jpa/logs # 相对于项目根路径
    name: ${logging.file.path}/application.log
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ssXXX} %clr(%5p) %clr(${PID:-}){magenta} %esb(){APPLICATION_NAME}%esb{APPLICATION_GROUP}[%15.15t] %clr(%-40.40logger{39}){cyan} : %m%n%wEx"
    file: "%d{yyyy-MM-dd'T'HH:mm:ssXXX} %5p ${PID:-} %esb(){APPLICATION_NAME}%esb{APPLICATION_GROUP}[%15.15t] %-40.40logger{39} : %m%n%wEx"
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/spring-%d{yyyy-MM-dd}-no-%i.log
      max-file-size: 10MB
      max-history: 7 # 单位为天
  level:
    sql: debug
    web: debug
    org.qiaice: debug

# spring 相关配置
spring:
  application:
    name: data_jpa
  jpa: # jpa 相关配置
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource: # datasource 相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_jpa?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: 040905
