# 日志相关配置
logging:
  level:
    sql: debug

# spring 相关配置
spring:
  application:
    name: data_jpa
  jpa: # jpa 相关配置
    hibernate:
      ddl-auto: create
  datasource: # datasource 相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_jpa?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: 040905
